In [11]:
import numpy 
n = numpy.arange(27) #--> ndarray object
n = n.reshape(3, 3, 3) #--> multi-dim object 
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
lst = [[123, 12, 123, 12, 12], [], []]
m = numpy.asarray(lst)
m 

array([list([123, 12, 123, 12, 12]), list([]), list([])], dtype=object)

In [23]:
#img --> ndarray
import cv2
img = cv2.imread("small-gray.png", 0) #0-grayscale_2d, 1-blue,green,red_3d
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
#ndarray --> img
cv2.imwrite("new-small-gray.png", img)

True

In [31]:
#splicing/indexing
img[0:2, 2:4] #row, column (by index)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [34]:
#iterating
for i in img.flat: print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [42]:
#stacking
ims1 = numpy.hstack((img, img, img)) #horizontal
ims2 = numpy.vstack((img, img, img)) #vertical

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [46]:
#splitting
lst = numpy.hsplit(ims, 5)  #into h sections
lst2 = numpy.vsplit(ims, 3) #into v sections

In [48]:
lst2

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182]], dtype=uint8)]